version: '3.8'

services:
  api:
    build: .
    networks:
      - backend-network
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/backend-app
    command: air ./cmd/main.go -b 0.0.0.0
  headless-shell:
    image: chromedp/headless-shell:latest
    networks:
      - backend-network
  mongodb:
    image: mongo:latest
    networks:
      - backend-network
    container_name: dev-mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/var/lib/mongodb/data
      - mongoconfig:/var/lib/mongodb/configdb

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  backend-network:
